### ISSUE TITLE
[BUG] - De rich 'more' knop werkt niet in modal (voor DSI2)

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-textarea#64]
**Omschrijf het probleem**
De ‘more’ knop met de 3 puntjes werkt niet binnen een modal. 
De knop wordt wel ‘enabled’, maar er wordt niets getoond.

Momenteel hebben we een workaround door de breedte van de modal te verhogen. 
`  dialog.style.overflow = 'visible';
  dialog.style.width = '95rem';`
 
**Hoe te reproduceren**

- Op DSI2 oefen of ontwikkel gaan
- Nieuw dossier aanmaken
- Nieuwe fase aanmaken --> hier kan je zien dat 'Dossier Informatie' een rich text area is 
  (_momenteel is dit dus gefixed, dus je zal de width van de dialog op 60rem moeten zetten bijvoorbeeld. Nu worden alle opties normaal getoond zonder de more knop._)

**Gewenst gedrag**
Opties tonen wanneer 'more' enabled wordt.

**Screenshots**
![image](https://user-images.githubusercontent.com/8820456/88284114-20555480-cced-11ea-9311-e612233c78f0.png)

**Omgeving (gelieve aan te vullen):**
 - Browser chrome

 - Versie component 
branch "github:milieuinfo/webcomponent-vl-ui-textarea#i-am-rich-baby" voor textarea
vl-ui-modal =  3.0.9

**Comment by coemans** [comment]
Het probleem is niet reproduceerbaar in isolatie, combinatie vl-ui-modal en vl-ui-textarea en zal in kader van dit issue in detail verder onderzocht worden op applicatie niveau.

**Comment by coemans** [comment]
Aangezien er een workaround is en een rich testarea in een modal waarschijnlijk niet de beste UI/UX optie is, parkeer ik het issue voorlopig.

**Comment by coemans** [comment]
Er was reeds een workaround en de toolbar kan nu ook gepersonaliseerd worden, waardoor de mogelijkheid bestaat om minder relevante toolbar items te verwijderen om zo het probleem ook te voorkomen.

Besproken met het team om voorlopig geen verdere actie te ondernemen waardoor dit ticket afgesloten zal worden.
