### ISSUE TITLE
[BUG] - rich text lijst met ander opties voor lijsten werkt niet in combinatie met modal

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-textarea#67]
**Omschrijf het probleem**
Wanneer rich-text in een modal zit en je probeert andere opties te kiezen voor een lijst in die rich-text dan zie je geen lijst met opties.

**Hoe te reproduceren**
Zet rich text in modal en probeer lijst met lege bolletjes te maken.

**Gewenst gedrag**
Lijst met verschillende opties voor een lijst, zien.

**Screenshots**
<img width="142" alt="Schermafbeelding 2020-08-11 om 11 30 51" src="https://user-images.githubusercontent.com/5698858/89882175-bed72600-dbc6-11ea-913f-fba4c2190d0a.png">
![image](https://user-images.githubusercontent.com/5698858/89882213-cc8cab80-dbc6-11ea-8753-d5cc3e53f1ba.png)

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2214
