### ISSUE TITLE
[BUG] - Typen/plakken achter link in rich-text maakt tekst ook deel van link

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-textarea#68]
**Omschrijf het probleem**
Wanneer we in een rich-text een link aanmaken en daarachter verder willen typen/een tekst plakken, dan wordt deze tekst deel van de link.

**Gewenst gedrag**
Dat link stopt na spatie, na plakken

**Comment by coemans** [comment]
@SBylemans kan je het probleem nog reproduceren? Ik op de (nieuwste) demo pagina niet:

Spatie:
![space](https://user-images.githubusercontent.com/11139249/90637137-e6179e00-e22b-11ea-82b4-568020f2e6ca.gif)

Copy paste:
![copypaste](https://user-images.githubusercontent.com/11139249/90637196-fdef2200-e22b-11ea-9841-34749754a3b5.gif)

**Comment by SBylemans** [comment]
@coemans lijkt idd opgelost.

**Comment by coemans** [comment]
Verder besproken en we zullen voorlopig afwachten of gebruikers dit ervaren als een bug.
