### ISSUE TITLE
[BUG] - Het wijzigen van het error attribuut heeft een toggle van error als gevolg

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-textarea#74]
**Omschrijf het probleem**
Wanneer we het 'error' attribuut 2 maal zetten op de component, is de error weg doordat in de component een toggle wordt toegepast bij het wijzigen zonder naar de waarde te kijken

**Hoe te reproduceren**
2 maal `.setAttribute('error',"")` toepassen op de component.

**Gewenst gedrag**
2 keer het attribuut zetten zou nog steeds de error rond de component moeten laten zien. Enkel het attribuut verwijderen zou ervoor moeten zorgen dat de error rond de component weg gaat.

**Omgeving (gelieve aan te vullen):**
Branch #i-am-rich-baby

**Comment by FreekRombauts** [comment]
@coemans , getest en gereviewed. Wijzigingen zijn ok.
