### ISSUE TITLE
[FEATURE] - Layout mogelijkheden via increase decrease indent

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-textarea#75]
**Wat moet er gebeuren**
mogelijkheid om text te identeren met de rich text component

**Comment by coemans** [comment]
@pharacyde ik heb voorzien dat vanaf heden de WYSIWYG toolbar zelf samengesteld kan worden omdat er anders te veel items gevisualiseerd worden die potentieel niet voor iedereen interessant zijn.

Het `data-vl-toolbar` attribuut kan gebruikt worden met o.a. onderstaande toolbar items maar in principe zijn al de TinyMCE items ondersteund:
* undo
* redo
* bold
* italic
* underline
* strikethrough
* h1
* h2
* h3
* h4
* h5
* h6
* vlLink
* blockquote
* hr
* numlist
* bullist
* outdent
* indent

**Comment by FreekRombauts** [comment]
@coemans , ziet er ok uit.
