### ISSUE TITLE
[BUG] - Focus call heeft geen effect op rich variant

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-textarea#79]
**Omschrijf het probleem**
focus call heeft geen effect op de component

**Hoe te reproduceren**
selecteer de component via dev tools, call focus().

**Comment by coemans** [comment]
Probleem lijkt zich te beperken tot de rich variant.

**Comment by FreekRombauts** [comment]
@coemans , getest in alle browsers. werkt.
