### ISSUE TITLE
[BUG] - Random errors in console log

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-textarea#80]
**Omschrijf het probleem**
bij focus out of bij updates zien we stacktraces in de console logging

```
tinymce.min.js:27 Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.isEditorUIElement (tinymce.min.js:27)
    at tinymce.min.js:27
    at E (tinymce.min.js:27)
    at Object.getParent (tinymce.min.js:27)
    at am (tinymce.min.js:27)
    at tinymce.min.js:27
    at Object.each (tinymce.min.js:27)
    at Object.hd (tinymce.min.js:27)
    at Ei.executeHandlers (tinymce.min.js:27)
    at HTMLDocument.s (tinymce.min.js:27)```

Komt voor in Safari / Chrome

**Comment by coemans** [comment]
@pharacyde ik kan het probleem lokaal en op de gepubliceerde demo pagina niet reproduceren. Lukt het jou om dit probleem boven te halen op de demo pagina?

**Comment by karol-depka** [comment]
Hi Folks. I just found this repo by googling (I have the same error). 
Looks like this is the root cause for You: https://github.com/tinymce/tinymce/issues/6093 
(hope it might help you)

**Comment by karol-depka** [comment]
I've made a workaround by linking to specific version:

  <script src="https://cdn.tiny.cloud/1/(YOUR_KEY)/tinymce/5.4.2/tinymce.min.js" referrerpolicy="origin"></script>

    https://github.com/tinymce/tinymce-dist/blob/master/changelog.txt
    https://github.com/tinymce/tinymce/pull/6133

**Comment by coemans** [comment]
Thank you @karol-depka for the spontaneous feedback. This issue was logged internally, but I haven't been able to reproduce it on our [demo page](https://webcomponenten.omgeving.vlaanderen.be/demo/vl-textarea.html). We use version ^5.4.2 so probably the reporter of this issue has a more recent version of TinyMCE.

Apparently they are solving the problem at TinyMCE, so we need some patience and use a fixed 5.4.2 version in the meantime.

**Comment by coemans** [comment]
@pharacyde met versie 5.5.1 van TinyMCE kan ik ook lokaal en op de demo pagina de problemen niet reproduceren. Als ik het goed begrijp is er verder geen nadelig gevolg gekoppeld aan het verschijnen van de console errors, dan wordt het moeilijk om hiervoor geautomatiseerde testen te schrijven. Indien nodig kan applicatief tijdelijk de 5.4.2 versie gebruikt worden. Aangezien TinyMCE het probleem aan het oplossen is en vermoedelijk de volgende release al een fix bevat, stel ik voor om verder niets te ondernemen.

**Comment by karol-depka** [comment]
Thank You, @coemans . I appreciate Your appreciation :). After some time of using 5.4.2, I think I can confirm the error was not happening. Good Luck with Your endeavours. I imagine the Reporter had 5.x+. Looking at the comments, looks like I should learn Dutch :).
(vriendelijke groeten :) )

**Comment by karol-depka** [comment]
By the way, You Guys are doing something related to the webpage of Vlaanderen?

**Comment by coemans** [comment]
@karol-depka thanks for the confirmation. We should communicate in English to use the power of the community, fortunately the stacktraces are traceable. Our components are written for and (partly) used by Flanders.
