### ISSUE TITLE
[BUG] - TinyMCE append div in body en neemt whitespace in beslag

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-textarea#81]
**Omschrijf het probleem**
Tinymce maakt extra divs aan in de body, waardoor hier extra whitespace gebruikt wordt

```
<div class="tox tox-silver-sink tox-tinymce-aux" style="position: relative;"></div>
```

waarschijnlijk moeten die divs daar niet komen.

**Hoe te reproduceren**
ga naar de demo pagina -> https://webcomponenten.omgeving.vlaanderen.be/demo/vl-textarea.html 
als je naar beneden scrollt zie je wat extra white space, deze komt door tinymce divs

**Comment by FreekRombauts** [comment]
@coemans , ziet er in orde uit.
